all: backward ModifedPicard Picard

backward: 
	cd celiasolution/BackwardDiff && mkdir -p output && make

ModifedPicard: 
	cd celiasolution/ModifiedPicard && mkdir -p output && make

Picard: 
	cd celiasolution/Picard && mkdir -p output && make

# plot: 
# 	cd celiasolution/Picard && mkdir -p output && make
